[font]
normal = { family = "DejaVuSansM Nerd Font", style = "Regular" }
size = 11

[window]
dimensions = { columns = 102, lines = 28 }

[keyboard]
bindings = [
	{ key = "+", mods = "Control", action = "IncreaseFontSize" },
	{ key = "-", mods = "Control", action = "DecreaseFontSize" }
]

# Colors Gruvbox

# Default colors
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black = '#1d2021'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

# Bright colors
[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'
