[[themes]]
name = "tokyo_night"
[themes.palette]
background = "#1a1b26"
foreground = "#d9e0ee"
black = "#000000"
blue = "#4c66f3"
cyan = "#00ffff"
green = "#4caf50"
magenta= "#d500f9"
red = "#f44336"
white = "#ffffff"
yellow = "#ffeb3b"
bright_black = "#2e3440"
bright_blue = "#5e81ac"
bright_cyan = "#8fbcbb"
bright_green = "#a3be8c"
bright_magenta = "#b48ead"
bright_red = "#bf616a"
bright_white = "#e5e9f0"
bright_yellow = "#ebcb8b"

[[themes]]
name = "gruvbox"
[themes.palette]
background = "#282828"
foreground = "#ebdbb2"
black = "#282828"
blue = "#83a598"
cyan = "#8ec07c"
green = "#8ec07c"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"
bright_black = "#928374"
bright_blue = "#83a598"
bright_cyan = "#8ec07c"
bright_green = "#8ec07c"
bright_magenta = "#d3869b"
bright_red = "#fb4934"
bright_white = "#f9f5d7"
bright_yellow = "#fabd2f"

[[themes]]
name = "everforest"
[themes.palette]
background = "#1d2b2a"
foreground = "#d3d7cf"
black = "#282c34"
blue = "#4c5c68"
cyan = "#6e8c8a"
green = "#a8c080"
magenta = "#d88bcf"
red = "#e56d76"
white = "#f8f8f2"
yellow = "#d4c56b"
bright_black = "#3c4741"
bright_blue = "#7398b7"
bright_cyan = "#a3c1b6"
bright_green = "#b0d56c"
bright_magenta = "#c68a9f"
bright_red = "#f28c7f"
bright_white = "#e0e4d8"
bright_yellow = "#E1D86D"

[[themes]]
name = "monokai"
[themes.palette]
background = "#272822"
foreground = "#f8f8f2"
black = "#000000"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#f92672"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"
bright_black = "#3e3d32"
bright_blue = "#66d9ef"
bright_cyan = "#a1efe4"
bright_green = "#a6e22e"
bright_magenta = "#f92672"
bright_red = "#f92672"
bright_white = "#f8f8f2"
bright_yellow = "#f4bf75"

