theme = "default"
client_id = "Lol-LMAO-ImNOTLEAKINGSHIT"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """

              {track}
              {album}

              {artists}

              {status} {metadata}"""
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "再"
pause_icon = "止"
liked_icon = "好"
border_type = "Plain"
progress_bar_type = "Rectangle"
cover_img_length = 9
cover_img_width = 4
cover_img_scale = 2.2
enable_media_control = true
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
default_device = "spotify-player"
notify_streaming_only = false
seek_duration_secs = 5

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
playback_window_position = "Top"
playback_window_height = 10

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "hephaestus"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
